#source :rubygems
source "http://rubygems.org"
gem 'sinatra'
gem 'haml'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-migrations'
gem 'rake'
gem 'rack-flash'
gem 'twitter'
gem 'oauth'
gem 'redis'
gem 'redis-namespace'
gem 'yajl-ruby'
gem 'rack'
gem 'resque'
gem 'unicorn'
#gem 'SystemTimer'

